### ISSUE TITLE
Unmapped reads not in the same order

### ISSUE THREAD

**Issue by prajkta9** [alexdobin/STAR#1134]
Hi,

I am using STAR v2.7.7a and I paired-end reads. I used `--outReadsUnmapped Fastx` to get the unmapped reads. I was expecting these reads to be in the same order, but this is not the case. I noticed this issue was present in older versions of STAR and was fixed but I am still having the same problem. Any idea on how to fix this?

These are the top 5 reads for the unmapped mates:
`Unmapped.out.mate1
@MG01HX01:1039:HCTMGCCX2:8:1103:17401:7233 0:N: 
CGACGCTCTTCCGATCTCGACGCTCTTCCGATCTCGACGCTCTTCCGCTCTCGACGCTCTTCCGCTCTCGCCGCCCCCCCGCTCTTTTTTTTGTTTGTTTTACTCAAGGGGAGACATCGGAAGAGCGTCGAGATCGGAAGAGCGTTGAGAT
+
AAFFFJAJFFJJJJFFFJJJJJJJJAFJJJ-AFJJA-7AJ-F-AJFF--A7<JJA-7-7---FA--7-7--77<-7----7-77--7-AAF<-AJ----7<-<--7A<7----7--<7FA77--7J-----7---7777A-7---------
@MG01HX01:1039:HCTMGCCX2:8:1103:19553:7233 0:N: 
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGTCATAAAAAGAAACAAAACAAAAAAAAAAAACA
+
AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJFJJJJJJJJJJJJJJJJJFA<FJJFFFJJJFFJAJJJJ<7<AFAFFFJJFJJJF--<<A---<<-<--7--<A--7-A<J<J--7-7---AF-<-F-7AA
@MG01HX01:1039:HCTMGCCX2:8:1103:23125:7233 0:N: 
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTGGCCGCCTTTTCAAGTTCGGAGGGCCCCCCTTTTGAACTCCTGTCCCCCGCGTTTTTCTCTTTTCCCTTTTTTTCTTTGAAAAAAATCTTGGCCTTGTTTGCTCCGCCGTTGT
+
AAFFFJJJJJJJJJJJJJJJFJJJJJJ-FFFJJJFJ<--<<7-7-<FJ<-<7-----7--7--AA--7-7-<---7-7<---7AAJA----7A------<F--<-7--<-----<----AJF<--7--<7--------7---7----77--
@MG01HX01:1039:HCTMGCCX2:8:1103:23267:7233 0:N: 
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGACGGAAGGGCCCCCCGTTTACCCCCCACCCCCCCCGGGTTTTCCCGAATGCCGTCTTCTTTTTAAAAAAAAAAAATTTTTAGTTATGATACATATAGACATAA
+
AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ---<<A-77--7---7-7--<-----7----77AJ---7-A---7------<<----77---<---7FJJJJ7-77-----7--7-------7-77---------
@MG01HX01:1039:HCTMGCCX2:8:1103:23287:7233 0:N: 
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGATCGGAAGAGCACCCCTCTGAACTCCAGTCCCCCGCGGTTATCCCGTATGCCGTCTTCTGCTTGAAAAAAACACACCCTTGACTGAATGCCAGAGAAACACCGTACCGGCT
+
AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFA-7F<F<----<---7-AA77----FJF--77AJJJ<-77F7----7F7<7<F---77---<FA<AJJJJ7<---<-A7--------7-------7----7--77-------
`
`Unmapped.out.mate2
@MG01HX01:1039:HCTMGCCX2:8:1102:15453:30404 1:N:  00
TGCTCTTCCGATCTCAGGAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCGCCGAGGTGAAGTTCGAGGGCGACACCCTGGTGAACCGCATCGAGCTGAAGGGCATCGACTTCAAGGAGGACGGCAACATCCTGGGGCA
+
AAFFFJFAJJ7FJJJFJAFFFJJFJJFJJJJJJJJJF<F<FJAJFJJA7FJ7JFFF<FJJJJJJJJ-<A<J-AJJFJJ7FJJJJFAAJJJJJJJJFFFJJJFJJJ-FJJJ-7FJJJFFAJFFFJJF7FJJJJ-FJFJ--7AAAFJJJJJJ-
@MG01HX01:1039:HCTMGCCX2:8:1102:20567:30404 1:N:  00
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGGGGGGAAGGGCCGCGGGGGGGGAAAGAGTGGCTGGCGCTGTGTAGATCTCGGTGGGCGCCGTTTTATTAAAAAAAAGTAATAACAGAGTTCTCCTAGCATAGAAA
+
AAFFFJJJJJJJJJJJJJJJJJJJJJJJJAJJJJJFJJJJJJFJ---------7-----7--A--7<7-7---7-7-7--7---------77F-777A-7A-<--7------7-7FFJJJ-7---77--7-7-----------------77
@MG01HX01:1039:HCTMGCCX2:8:1102:20649:30404 1:N:  00
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
+
AA-AA-AFFJ-FFJJFJFJFJAJFJJFFF<FJFJ<FJJJFJJJJFAJFJJFJJJJJJJFJJFFJJJJFJFJJJFJFF<JJFJJFJFAFFAJJJJJJJJJFF<FAFAJFAAJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ
@MG01HX01:1039:HCTMGCCX2:8:1102:24485:30404 1:N:  00
ATCGAGAAGTGCTTGCTGGTGGGGATACGCGTGAAGGACGACTTATGGAAGAATTTCGAAGCGACGGCGACTTTGCTTGCCGATTTGAGTGATGTAGATAAGGTCCTGACTGAGGAGAGAGAGGTAGGAAGACGAAGAGAGGTCACGGTGA
+
AAFFFJJJJJJJJJJJJJJJJJJJFFJJJJJJJFFJJFJJJJJJJJJJJJJJFJJJJJJFJJJFJJJJJAJJJJJJJJJJJJ<AJJJAJJJFFJJAJFJFJJJJJJJJFJJJFFJ-FFFAJFJJFJJJJJJJJJJFJAJJJJJJJJJJJJF
@MG01HX01:1039:HCTMGCCX2:8:1102:26068:30404 1:N:  00
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
+
AAAAAAFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJFJFFFFAAFAFAAFF--F<FFAFFAAJ<<<<AF<AFAJJ<AFJFFFFJJJF<FAFAFFA<JF<A<AJ<F<A---F---7-<`

**Comment by alexdobin** [comment]
Hi @prajkta9 

I thought that I fixed this issue in 2.6.1d, and I have not received any complaints since.
It's strange that the output in ```Unmapped.out.mate1``` does not contain the ```00``` -like tags in each read ID line - they are always output for PE reads.

Could you re-run it with a small subset of reads, and the output still does not contain ```00``` tags, please send me the Log.out file.

Cheers
Alex

**Comment by prajkta9** [comment]
Hi @alexdobin,

Sorry for the late response. I did re-run the code with Top 25 reads only. The unmapped reads one gave me one output this time `Unmapped.out.mate1`. No, `Unmapped.out.mate2` file. 
The `Unmapped.out.mate1` still does not contain `00` tags. 
Log.out file: 
[Sample1Top25ReadsLog.out.txt](https://github.com/alexdobin/STAR/files/5905269/Sample1Top25ReadsLog.out.txt)

Thank you.

**Comment by alexdobin** [comment]
Hi @prajkta9 

for PE read mapping, you need to use space (not comma) to separate reads in ```--readFilesIn```:
```
--readFilesIn /Users/pk/Downloads/Sample1Top25Reads_R1.fastq.gz    /Users/pk/Downloads/Sample1Top25Reads_R2.fastq.gz
```

Cheers
Alex

**Comment by alexdobin** [comment]
Hi @prajkta9 

the comma-separated list has a different meaning than the space-separated list. 
The space-separated list is for Read1 and Read2 of PE reads. 
The comma-separated list is for >=2 "lanes" that you want to map together. If you have one comma-separated list, it will be mapped as SE reads.
Since you have PE reads, you would need to realign with the space-separated list.

**Comment by prajkta9** [comment]
Thanks a lot, @alexdobin for the clarification. I will re-align them.
