### ISSUE TITLE
Unable to coordinate sort Aligned.out.bam using bamsort for STAR versions 2.5.1a and b

### ISSUE THREAD

**Issue by amatchan** [alexdobin/STAR#146]
Hi there,
I've developed a pipeline using STAR that outputs both Aligned.out.bam as well as the transcriptome mapped bam. I've tried using the BAM SortedByCoordinate option but, even when dropping threads to 4, it requires over 60GB memory. As my pipeline is likely to be running many samples in parallel (over 100 wouldn't be unusual) it's actually a better use of resources for me to output unsorted BAMs and then run biobambam bamsort to coordinate sort them. Then I only need to request ~34GB memory per sample.

My pipeline has been working fine this way until I tried upgrading to the latest version of STAR. The bamsort command on Aligned.out.bam fails with the folllowing error message:
'Invalid alignment: Invalid next segment mapping position'

The command I'm running is:
bamsort I=Aligned.out.bam fixmate=1 inputformat=bam level=1 tmpfile=tmp O=Aligned.sorted.out.bam

I tried with STAR v2.5.1a and got the same problem.
When I use v2.5.0c bamsort completes successfully.

I tried investigating this a bit. When I ran Picard ValidateSamFile over the BAM that bamsort's rejecting, I get this output (in summary mode):
## HISTOGRAM

java.lang.String
Error Type
Count
ERROR:INVALID_ALIGNMENT_START
358427
ERROR:MATE_NOT_FOUND
334200
ERROR:MISMATCH_MATE_ALIGNMENT_START
806078
ERROR:MISSING_PLATFORM_VALUE
1

and in verbose mode here is part of the output:
ERROR: Record 4400832, Read name HS20_13617:3:2110:17629:19870, Mate Alignment start (1510199307) must be <= reference sequence length (50818468) on reference chr22
ERROR: Record 4400832, Read name HS20_13617:3:2110:17629:19870, Mate alignment does not match alignment start of mate
ERROR: Record 4621198, Read name HS20_13617:3:1215:4258:97632, Mate alignment does not match alignment start of mate
ERROR: Record 4626128, Read name HS20_13617:3:2315:18668:83386, Mate Alignment start (1676502111) must be <= reference sequence length (58617616) on reference chr19

I haven't managed to resolve the problem though. Have I missed a parameter value that needs changing in the latest versions of STAR?

Thanks
Angela

**Comment by alexdobin** [comment]
Hi Angela,

let's first solve the 2nd problem - the improper SAM formatting (the problem with RAM for BAM sorting should be solvable too).

Could you please send me the Log.out file, and also grep the HS20_13617:3:2110:17629:19870 lines from the SAM file.

Cheers
Alex

**Comment by amatchan** [comment]
Hi Alex,
thank you for responding so promptly.
A
[Log.out.gz](https://github.com/alexdobin/STAR/files/256931/Log.out.gz)
ttached is Log.out and here are the grepped lines from Aligned.out.bam:

HS20_13617:3:2110:17629:19870	73	chr22	41930763	255	1S74M	*	0	0	AGCCCACCTTGGCCTCCCAAAGTGCTGGGATTACAGGCACGAGCCACCACTCCTGGCCTAATTTCTTTATTCAAG	CCCFFFFFHHHHHJJJJJJJJJHIIIJJJJJIJJJJJIJJJJJJJJJJJJJJJJJJJJJGHHHHHFFFFFFFEEE	NH:i:1	HI:i:1	NM:i:2	MD:Z:6T31T35	AS:i:68	RG:Z:1

HS20_13617:3:2110:17629:19870	133	*	0	0	*	chr22	1510199307	0	CTCCATCTCAAAAAAAAAAAAAAAAAAAACTTAAAAAAAAAAATTAGGCCAGGGGGGGGGGCCCGGGCCTTTAAC	CCCFFFFFHHHHHJJJJJJJJJJHFDB2,'5:((3+8980960(((++(3(+2&5568577&&&)&&&&(((++(	NH:i:0	HI:i:0	AS:i:68	nM:i:2	uT:A:4	RG:Z:1

**Comment by alexdobin** [comment]
Hi Angela,

thanks a lot for reporting this proble, I have fixed it - please try the latest release and let me know whether it worked:
https://github.com/alexdobin/STAR/releases/tag/2.5.2a

Cheers
Alex

**Comment by amatchan** [comment]
Ok great, thanks Alex, will do.

**Comment by amatchan** [comment]
I've retested with STAR 2.5.2a today and bamsort worked successfully. Thanks very much for the fix.
Angela

**Comment by alexdobin** [comment]
Hi Angela,

great, thanks for letting me know.

Going on to the sorting problem. When you try to sort you file with STAR, does it ask you to increase the RAM limit to 60GB. It should not happen with the later versions except in rare cases - please send me the corresponding Log.out file.

Cheers
Alex

**Comment by code-is-cold** [comment]
Hi Alex,

I still get this bug when i used STAR 2.5.2a version, the mate mapped to different chromosome still get the greater coordinate then chromosome length.

alignment record:
HISEQ:604:C7A86ANXX:6:1102:4986:8056    65      3       141264214       255     109M    12      630645564       0       AGCTTCCAATCATAACAAACACCAAGCGGGAGCAGGTGTCCTACATGGCAGGAGCAGGAACAGGAGAGAGAGTGGGGAGGTACTACATACTTTTTTTTTTTTTTTTTTT   BBBBBFFFFFFBBBFFFFFFFFFFFFFFFFFFFBFFFFF/FFFFFB/FFFFFFB<FFFFFBFFBFF/FFBFFFBFFFFFFFFFFFFFFFFFFFF<FFFFFFFFFFFFBF   NH:i:1  HI:i:1  AS:i:107        nM:i:0  NM:i:0
HISEQ:604:C7A86ANXX:6:1102:4986:8056    129     12      110289724       255     125M    3       1836287318      0       CTCACTGCAACCTCCACCTCCCGGGTTCAAGCGATTCTCCTGCCTCAGCCTCCTAAGTAGCTGGAACTACAGGCGTGCGCCACCATGCCCAGCTAATTTTTTATATTTTTAGTAGCGATGGGGTT   BBBBB/BFFFFFFFFFFFFFFFFF/<<<BFFFFFFBFFFFFFFF</FFFFFFFFF<FFFFFBBB<BFBFF/FFF<FBFFFFFFFBBFFFF/<BFFFBFFBFFFF/BFFFF<<FBFFFFFFFFFFB   NH:i:1  HI:i:1  AS:i:121        nM:i:1  NM:i:1

really need your help, thanks!
